name = "Create Pack 1.20"
author = "MarioAndWeegee3"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82771f9e585f154163b1290bfc29fa52b0bbb0ae311e9b3d3074ae08a09cf228"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
