name = "Create Pack 1.20"
author = "MarioAndWeegee3"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "750d4f8b9905a02b387f9a9e0f4d24d47848cdf65be2595eea14e1efc34350ae"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"
